fix: Make ~/bin/code POSIX compliant

diff --git a/bin/code b/bin/code
--- a/bin/code
+++ b/bin/code
@@ -1,38 +1,44 @@
-#!/usr/bin/env zsh
+#!/bin/sh
 # code - Visual Studio Code wrapper
-# NOTE: depends on ~/.zshenv, particularly $OS, $WSL, $WSL_USER and $WSL_MOUNT
+# NOTE: Depends on my ~/.zsh* for $OS, $WSL, etc.
 
 VSCODE=
 find_vscode() {
 	for p in "$@"; do
 		if [ -x "$p" ]; then
-			VSCODE="$p" ; break
+			VSCODE="$p"
+			break
 		fi
 	done
 }
 
 case "$OS" in
 	linux|bsd)
-		if [[ -z $WSL ]]; then
+		if [ -z "$WSL" ]; then
 			find_vscode \
-				{/usr,/usr/local}/bin/code
+				/usr/bin/code \
+				/usr/local/bin/code \
+				"$HOME"/.opt/vscode/bin/code
 		else 
-			# inside WSL run Windows wrapper
 			find_vscode \
-				"$WSL_MOUNT"/c/{Program\ Files,Users/"$WSL_USER"/AppData/Local/Programs}/Microsoft\ VS\ Code/bin/code
-		fi	
+				"$WSL_MOUNT"/c/Program\ Files/Microsoft\ VS\ Code/bin/code
+				"$WSL_MOUNT"/c/Users/"$WSL_USER"/AppData/Local/Programs/Microsoft\ VS\ Code/bin/code
+		fi
 		;;
-	macos) 
+	macos)
 		find_vscode \
 			/usr/local/bin/code \
-			{/Users/"$USER",}/Applications/{,Developer/}Visual\ Studio\ Code.app/Contents/Resources/app/bin/code
+			/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code
+			/Applications/Developer/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code
+			/Users/"$USER"/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code
+			/Users/"$USER"/Applications/DeveloperVisual\ Studio\ Code.app/Contents/Resources/app/bin/code
 		;;
 	*)
-		echo >&2 "${0##*/}: unsupported OS=${OS:-unset}" ; exit 1
+		echo >&2 "code: unsupported OS=$OS"; aexit 1
 		;;
 esac
 
-if [[ -z $VSCODE ]]; then
-	echo >&2 "${0##*/}: Microsoft VS Code not found" ; exit 1
+if [ -z "$VSCODE" ]; then
+	echo >&2 "code: Microsoft VS Code not found" ; exit 1
 fi
 exec "$VSCODE" "$@"
