feat: Implement add/delete git-dir

diff --git a/bin/git-dir b/bin/git-dir
--- a/bin/git-dir
+++ b/bin/git-dir
@@ -1,20 +1,55 @@
-#!/bin/bash
-# gitdir - add local gitdir to .gitconfig_local
-# Usage: gitdir add|del|delete /path/to/dir
+#!/bin/bash -e
+# Add local directory to .gitdirs and include ~/.gitconfig_dir_suffix for it.
+# Usage: git dir add|delete /path/to/dir suffix
 
-[ $# -eq 2 ] && [ -d $2 ] || exit 1
+[ $# -lt 2 ] && {
+    >&2 echo -e "usage: dir add /path suffix\n       dir delete /path"
+    exit 1
+}
+[ -d "$2" ] || {
+    >&2 echo "git: directory $2 does not exist"
+    exit 1
+}
 
-# If directory is in home use `~` in .gitdirs
-GITDIR=${2/#$HOME/\~}
+DIR=${2/#~/$HOME}
 
-# TODO Make add|del work
+CUR=
+NEW=
+case "$1" in
+    add)
+        [ $# -eq 3 ] || {
+            >&2 echo "git: suffix argument is missing"
+            exit 1
+        }
+        [ -e ~/.gitdirs ] || {
+            cat >> ~/.gitdirs <<EOF
+; ~/.gitdirs - Per-directory git configurations
+; vim:set ft=gitconfig:
 
-[ !-r $1/.gitconfig ] && "WARNING: $1/.gitconfig doesn't exist yet.."
-
-cat >>~/.gitdirs <<EOF
-[includeIf "gitdir:$1/"]
-    path = $1/.gitconfig
+; NOTE: This file is auto-updated by ~/bin/git-dir script. Put custom lines
+; on the top
 
 EOF
+        }
+        NEW="[includeIf \"gitdir:$DIR\"]\n\tpath = ~/.gitconfig_dir_$3"
+        ;;
 
-echo "SUCCESS: $1/ local .gitconfig will be applied (if it exists)."
+    del*)
+        [ -e ~/.gitdirs ] || exit 0
+        NEW=
+        ;;
+esac
+
+SKIP=
+while IFS= read -r L; do
+    case "$L" in
+        \[*)
+            SKIP=
+            if [[ $L =~ ^\[includeIf\ \"gitdir:$DIR/?\" ]] ; then
+                SKIP=1
+            fi
+            ;;
+    esac
+    [ -z $SKIP ] && CUR="$CUR\n$L"
+done < ~/.gitdirs
+echo -e "$CUR\n$NEW" > ~/.gitdirs
